# Generated by Django 5.2.3 on 2025-06-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_registered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='member',
            name='method_of_payment',
            field=models.CharField(choices=[('zaad', 'Zaad'), ('edahab', 'Edahab'), ('bank', 'Bank'), ('cash', 'Cash')], default='cash', max_length=10),
        ),
    ]
