# Generated by Django 5.2.3 on 2025-06-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_amount_paid_member_method_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='currency',
            field=models.CharField(choices=[('usd', 'Dollar'), ('sls', 'Somaliland Shilling')], default='usd', max_length=3),
        ),
        migrations.AlterField(
            model_name='member',
            name='method_of_payment',
            field=models.CharField(choices=[('zaad shilling', 'Zaad Shilling'), ('zaadDollar', 'Zaad Dollar'), ('edahab shilling', 'Edahab Shilling'), ('edahabDollar', 'Edahab Dollar'), ('bank shilling', 'Bank Shilling'), ('bankDollar', 'BankDollar'), ('cash shilling', 'Cash Shilling'), ('cash dollar', 'Cash Dollar')], default='cash', max_length=1000),
        ),
    ]
